---
# Run sysbench test
- name:  Setup PVCs to run test on
  k8s:
    state: present
    definition: "{{ lookup('template', 'common-objects.yaml.j2') }}"

- name: Wait few seconds for the PVC 
  pause:
    seconds: 60

- name: Create logs directory
  ansible.builtin.file:
    path: '{{ logfolder }}'
    state: directory
    mode: '0755'

- name: Get first uid from project range
  shell: oc get -o=jsonpath="{..openshift\.io/sa\.scc\.uid-range}" project {{ storage_perf_namespace }} | cut -d '/' -f 1
  register: target_uid_output

- name: Set target uid for the pods
  set_fact:
    target_uid_reader: "{{ target_uid_output.stdout|int }}"  

- name: set up scc for RWO
  block:
    - name: create custom scc
      k8s:
        state: present
        definition: "{{ lookup('template', 'fsgroup-scc.yaml.j2') | from_yaml }}"
   # - name: create custom sa
   #   shell: oc create sa fsgroup-sa -n {{ storage_validation_namespace }}
   # - name: add scc to custom sa
   #   shell: oc adm policy add-scc-to-user fsgroup-scc system:serviceaccount:{{ storage_validation_namespace }}:fsgroup-sa  
  rescue:
    - debug:
        msg: "set up scc for fsgroup failed"
