---
# Run sysbench test
- name:  Run sysbench random write RWX test
  k8s:
    state: present
    definition: "{{ lookup('template', 'sysbench_random_write_rwx.yaml.j2') }}"
    wait: yes
    wait_timeout: 7200
    wait_condition:
      type: Complete
      status: "True"

- name: Get logs of the sysbench random write pod for RWX
  community.kubernetes.k8s_log:
    namespace: "{{ storage_perf_namespace }}"
    label_selectors:
    - job-name=sysbench-random-write-rwx
  register: logx

- name: Save random write Log to local file
  local_action: 
    module: copy 
    content: "{{ logx }}"
    dest: "{{ logfolder }}/random_write_rwx.json"
