---
# Run sysbench test
- name:  Run sysbench random read RWO test
  k8s:
    state: present
    definition: "{{ lookup('template', 'sysbench_random_read_rwo.yaml.j2') }}"
    wait: yes
    wait_timeout: 7200
    wait_condition:
      type: Complete
      status: "True"

- name: Get logs of the sysbench random read pod for RWO
  community.kubernetes.k8s_log:
    namespace: "{{ storage_perf_namespace }}"
    label_selectors:
    - job-name=sysbench-random-read-rwo
  register: logo

- name: Save Log to local file
  local_action:
    module: copy
    content: "{{ logo }}"
    dest: "{{ logfolder }}/random_read_rwo.json"
